# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"train": "vae.ipynb",
         "test": "vae.ipynb",
         "plot_latent": "core.ipynb",
         "plot_test": "core.ipynb",
         "Recall": "recall.ipynb",
         "PriorityRecall": "recall.ipynb",
         "VAE": "vae.ipynb",
         "loss_function": "vae.ipynb"}

modules = ["core.py",
           "recall.py",
           "vae.py"]

doc_url = "https://CoAxLab.github.io/newremagine/"

git_url = "https://github.com/CoAxLab/newremagine/tree/master/"

def custom_doc_links(name): return None
